apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diplogpvc
  namespace: ada-namespace
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

