apiVersion: v1
kind: Service
metadata:
  name: spring-react-service
  namespace: ada-namespace
spec:
  type: NodePort
  selector:
    app: spring-react-demo
  ports:
  - name: http
    port: 8073 
    targetPort: 8073
    protocol: TCP

